In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
df=pd.read_csv(r"C:\Users\Supravata\Desktop\DATA_ANALYTICS_UDEMY\Projects by me\Banglore\Bengaluru_House_Data.csv")
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [4]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [5]:
df[df['size'].isnull()]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
579,Plot Area,Immediate Possession,Sarjapur Road,NaN,Asiss B,1200 - 2400,NaN,NaN,34.185
1775,Plot Area,Immediate Possession,IVC Road,NaN,Orana N,2000 - 5634,NaN,NaN,124.000
2264,Plot Area,Immediate Possession,Banashankari,NaN,NaN,2400,NaN,NaN,460.000
2809,Plot Area,Immediate Possession,Sarjapur Road,NaN,AsdiaAr,1200 - 2400,NaN,NaN,28.785
2862,Plot Area,Immediate Possession,Devanahalli,NaN,Ajleyor,1500 - 2400,NaN,NaN,46.800
5333,Plot Area,Immediate Possession,Devanahalli,NaN,Emngs S,2100 - 5405,NaN,NaN,177.115
6423,Plot Area,Immediate Possession,Whitefield,NaN,SRniaGa,2324,NaN,NaN,26.730
6636,Plot Area,Immediate Possession,Jigani,NaN,S2enste,1500,NaN,NaN,25.490
6719,Plot Area,Immediate Possession,Hoskote,NaN,SJowsn,800 - 2660,NaN,NaN,28.545
7680,Plot Area,Immediate Possession,Kasavanhalli,NaN,NaN,5000,NaN,NaN,400.000
8306,Plot Area,Immediate Possession,Anekal,NaN,Vaensnd,1453,NaN,NaN,16.500
8565,Plot Area,Immediate Possession,Carmelaram,NaN,Ocezes,2000,NaN,NaN,120.000
8703,Plot Area,Immediate Possession,Mysore Road,NaN,Naoden,1200 - 2400,NaN,NaN,42.300
10634,Plot Area,Immediate Possession,Rajankunte,NaN,NaN,1575,NaN,NaN,31.110
11019,Plot Area,Immediate Possession,Yelahanka,NaN,Saaveha,1200 - 1800,NaN,NaN,12.750
11569,Plot Area,Immediate Possession,Hosur Road,NaN,AVeldun,1350,NaN,NaN,8.440

In [6]:
df=df.dropna(subset=['size'])

In [7]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [8]:
df[df['size'].isnull()]

Empty DataFrame
Columns: [area_type, availability, location, size, society, total_sqft, bath, balcony, price]
Index: []

In [9]:
df[df['society'].isnull()]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
8,Super built-up Area,Ready To Move,Marathahalli,3 BHK,NaN,1310,3.0,1.0,63.25
9,Plot Area,Ready To Move,Gandhi Bazar,6 Bedroom,NaN,1020,6.0,NaN,370.00
10,Super built-up Area,18-Feb,Whitefield,3 BHK,NaN,1800,2.0,2.0,70.00
...,...,...,...,...,...,...,...,...,...
13310,Super built-up Area,Ready To Move,Rachenahalli,2 BHK,NaN,1050,2.0,2.0,52.71
13311,Plot Area,Ready To Move,Ramamurthy Nagar,7 Bedroom,NaN,1500,9.0,2.0,250.00
13312,Super built-up Area,Ready To Move,Bellandur,2 BHK,NaN,1262,2.0,2.0,47.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [10]:
df['society'].notna().mode()[0]

np.True_

In [11]:
df['society']=df['society'].fillna(df['society'].mode()[0])

In [12]:
df[-df['society'].notna()]

Empty DataFrame
Columns: [area_type, availability, location, size, society, total_sqft, bath, balcony, price]
Index: []

In [13]:
df['society'].isnull().sum()

np.int64(0)

In [14]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,GrrvaGr,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,GrrvaGr,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,GrrvaGr,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,GrrvaGr,550,1.0,1.0,17.00

In [15]:
df[-df['location'].notna()]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
568,Super built-up Area,Ready To Move,NaN,3 BHK,Grare S,1600,3.0,2.0,86.0

In [16]:
df['location']=df['location'].fillna(df['location'].mode()[0])

In [17]:
df[-df['location'].notna()]

Empty DataFrame
Columns: [area_type, availability, location, size, society, total_sqft, bath, balcony, price]
Index: []

In [18]:
df.isnull().sum()

area_type         0
availability      0
location          0
size              0
society           0
total_sqft        0
bath             57
balcony         593
price             0
dtype: int64

In [19]:
df[-df['bath'].notna()]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
56,Built-up Area,20-Feb,Devanahalli,4 Bedroom,BrereAt,3010 - 3410,NaN,NaN,192.000
81,Built-up Area,18-Oct,Hennur Road,4 Bedroom,Gollela,2957 - 3450,NaN,NaN,224.500
224,Super built-up Area,19-Dec,Devanahalli,3 BHK,Jurdsig,1520 - 1740,NaN,NaN,74.820
344,Super built-up Area,21-Dec,Kanakpura Road,1 BHK,PrarePa,525,NaN,NaN,21.530
669,Super built-up Area,18-Dec,JP Nagar,5 BHK,Pehtsa,4400 - 6640,NaN,NaN,375.000
702,Super built-up Area,18-Dec,JP Nagar,5 BHK,Pehtsa,4400 - 6800,NaN,NaN,548.500
801,Super built-up Area,18-Dec,JP Nagar,4 BHK,Pehtsa,4000 - 5249,NaN,NaN,453.000
941,Super built-up Area,Ready To Move,Whitefield,4 Bedroom,PrOakSi,3606 - 5091,NaN,NaN,304.000
1264,Built-up Area,18-May,Hennur,3 Bedroom,Asoilul,2264,NaN,NaN,155.000
1267,Super built-up Area,18-Jun,Yelahanka,3 BHK,Shalkri,1440 - 1884,NaN,NaN,67.980
1686,Super built-up Area,21-Dec,Whitefield,1 BHK,SudenEd,660 - 670,NaN,NaN,28.585
1724,Super built-up Area,Ready To Move,Thanisandra,1 BHK,Bhmesy,620 - 933,NaN,NaN,48.145
1765,Super built-up Area,19-Dec,Binny Pete,4 BHK,Shestlo,2695 - 2940,NaN,NaN,204.000
1852,Super built-up Area,19-Jun,Yelahanka,4 BHK,Vaaram,3450 - 3472,NaN,NaN,173.000
2500,Super built-up Area,22-May,Jakkur,4 BHK,SoineC,2249.81 - 4112.19,NaN,NaN,260.500
2563,Super built-up Area,Ready To Move,Rajaji Nagar,4 BHK,PhestOn,3436 - 3643,NaN,NaN,424.500
2944,Super built-up Area,18-Dec,Kudlu Gate,3 BHK,Sanzaat,1564 - 1850,NaN,NaN,99.745
2998,Super built-up Area,19-May,Sarjapur Road,3 BHK,Klark L,1446 - 1506,NaN,NaN,98.940
3370,Super built-up Area,Ready To Move,Kanakpura Road,3 BHK,Wiowsri,1430 - 1630,NaN,NaN,66.400
3544,Super built-up Area,19-Mar,Hennur Road,3 BHK,Puachal,1482 - 1846,NaN,NaN,93.865
3598,Super built-up Area,18-Jun,Haralur Road,4 BHK,SNnia E,2805 - 3565,NaN,NaN,175.000
3862,Super built-up Area,Ready To Move,Jigani,4 Bedroom,Prllasw,3293 - 5314,NaN,NaN,226.000
4210,Super built-up Area,Ready To Move,Malleshwaram,3 BHK,Sariaat,2215 - 2475,NaN,NaN,293.000
4346,Super built-up Area,18-Dec,Whitefield,3 BHK,Prtates,1650 - 2538,NaN,NaN,113.190
4843,Super built-up Area,18-Mar,Bhoganhalli,4 BHK,Rosha I,1974 - 2171,NaN,NaN,111.000
4894,Super built-up Area,Ready To Move,Bommanahalli,3 BHK,SNeur G,1360 - 1890,NaN,NaN,87.720
4995,Super built-up Area,18-Mar,Hebbal,3 BHK,SNontle,2466 - 2856,NaN,NaN,226.500
5464,Super built-up Area,18-Sep,KR Puram,3 BHK,MCnexva,1310 - 1615,NaN,NaN,62.810
5498,Built-up Area,Ready To Move,Chandapura,4 Bedroom,MRowsea,1782 - 2000,NaN,NaN,66.165
5747,Super built-up Area,18-Apr,Kanakpura Road,1 BHK,PrarePa,525,NaN,NaN,27.000
5918,Super built-up Area,Ready To Move,Sarjapur Road,4 BHK,Klark L,4260 - 4408,NaN,NaN,338.000
6256,Built-up Area,Ready To Move,Electronic City Phase II,4 Bedroom,Shrds O,3500 - 3600,NaN,NaN,167.500
6343,Super built-up Area,18-May,KR Puram,3 BHK,TGasyhu,1482 - 1684,NaN,NaN,70.445
6481,Super built-up Area,18-Jun,Chandapura,3 BHK,SuVue S,1100 - 1225,NaN,NaN,30.215
6778,Super built-up Area,Ready To Move,Old Madras Road,4 BHK,Saciatt,4050 - 4075,NaN,NaN,341.000
6873,Super built-up Area,18-Mar,JP Nagar,3 BHK,Shestut,1750 - 2640,NaN,NaN,152.000
6971,Super built-up Area,18-Dec,Whitefield,3 BHK,BSlasin,1390 - 1600,NaN,NaN,61.280
7398,Super built-up Area,18-Dec,JP Nagar,3 BHK,Pehtsa,3103 - 3890,NaN,NaN,237.500
7623,Super built-up Area,Ready To Move,Electronics City Phase 1,3 BHK,Shitt S,1450 - 1595,NaN,NaN,60.750
7921,Super built-up Area,18-Mar,Sarjapur Road,3 BHK,PualeSk,1618 - 1929,NaN,NaN,85.125
8020,Super built-up Area,22-May,Jakkur,4 BHK,SoineC,2249.81 - 4112.19,NaN,NaN,229.000
8056,Super built-up Area,Ready To Move,Jakkur,3 BHK,BrdgeNo,1610 - 1880,NaN,NaN,98.485
8275,Super built-up Area,21-Dec,Kanakpura Road,1 BHK,PrarePa,525,NaN,NaN,29.250
8289,Super built-up Area,18-Apr,Kanakpura Road,2 BHK,PrarePa,700 - 900,NaN,NaN,41.145
8472,Super built-up Area,18-Dec,Sarjapur,4 BHK,Kinuerg,1925 - 2680,NaN,NaN,80.590
8783,Super built-up Area,18-Dec,Whitefield,3 BHK,BSlasin,1390 - 1600,NaN,NaN,60.550
9129,Super built-up Area,18-May,Mysore Road,3 BHK,Brama P,1410 - 1710,NaN,NaN,83.300
9437,Built-up Area,18-May,Hennur,4 Bedroom,Asoilul,2557,NaN,NaN,170.000
9699,Super built-up Area,18-Jul,Bannerghatta,4 BHK,Mamespa,1791 - 4000,NaN,NaN,246.000
10330,Super built-up Area,Ready To Move,Kanakpura Road,3 BHK,Wiowsri,1430 - 1630,NaN,NaN,70.990
10553,Built-up Area,Ready To Move,Sarjapur Road,4 Bedroom,AztheBr,3418,NaN,NaN,222.000
10726,Super built-up Area,18-Mar,Sarjapur Road,3 BHK,PualeSk,1618 - 1929,NaN,NaN,102.920
11297,Super built-up Area,18-Dec,Hennur,4 BHK,Exitym,3484 - 3550,NaN,NaN,161.500
11496,Super built-up Area,21-Dec,Kanakpura Road,1 BHK,PrarePa,525,NaN,NaN,27.000
12768,Built-up Area,18-Mar,Bettahalsoor,5 Bedroom,Toainnt,3210,NaN,NaN,353.000
12861,Super built-up Area,21-Dec,KR Puram,4 BHK,Moquach,2204 - 2362,NaN,NaN,121.000
13240,Super built-up Area,Ready To Move,Devanahalli,1 BHK,Pardsri,1020 - 1130,NaN,NaN,52.570

In [20]:
print(df['bath'].value_counts())

bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
27.0       1
14.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64

In [21]:
df['bath']=df['bath'].fillna(df['bath'].median())

In [22]:
df['bath'].isnull().sum()

np.int64(0)

In [23]:
df['bath']=df['bath'].astype(int)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13304 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13304 non-null  object
 1   availability  13304 non-null  object
 2   location      13304 non-null  object
 3   size          13304 non-null  object
 4   society       13304 non-null  object
 5   total_sqft    13304 non-null  object
 6   bath          13304 non-null  int64
 7   balcony       12711 non-null  float64
 8   price         13304 non-null  float64
dtypes: float64(2), int64(1), object(6)
memory usage: 1.0+ MB

In [25]:
df.isnull().sum()

area_type         0
availability      0
location          0
size              0
society           0
total_sqft        0
bath              0
balcony         593
price             0
dtype: int64

In [26]:
df[df['balcony'].isnull()]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
6,Super built-up Area,18-May,Old Airport Road,4 BHK,Jaades,2732,4,NaN,204.00
7,Super built-up Area,Ready To Move,Rajaji Nagar,4 BHK,Brway G,3300,4,NaN,600.00
9,Plot Area,Ready To Move,Gandhi Bazar,6 Bedroom,GrrvaGr,1020,6,NaN,370.00
34,Built-up Area,Ready To Move,Kasturi Nagar,3 BHK,Kantsce,1925,3,NaN,125.00
40,Built-up Area,Ready To Move,Murugeshpalya,2 BHK,Gentson,1296,2,NaN,81.00
...,...,...,...,...,...,...,...,...,...
13277,Plot Area,Ready To Move,Kundalahalli Colony,7 Bedroom,GrrvaGr,1400,7,NaN,218.00
13279,Plot Area,Ready To Move,Vishwanatha Nagenahalli,6 Bedroom,GrrvaGr,1200,5,NaN,130.00
13306,Plot Area,Ready To Move,Rajarajeshwari Nagara,4 Bedroom,GrrvaGr,1200,5,NaN,325.00
13309,Super built-up Area,Ready To Move,Yeshwanthpur,3 BHK,IBityin,1675,3,NaN,92.13
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,GrrvaGr,3600,5,NaN,400.00

In [27]:
df['balcony'].value_counts()

balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64

In [28]:
df['balcony']=df['balcony'].fillna(df['balcony'].median())

In [29]:
df[df['balcony'].isnull()]

Empty DataFrame
Columns: [area_type, availability, location, size, society, total_sqft, bath, balcony, price]
Index: []

In [30]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,GrrvaGr,1440,2,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,GrrvaGr,1200,2,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,GrrvaGr,3600,5,2.0,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,GrrvaGr,550,1,1.0,17.00

In [31]:
df['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      shape=(2110,), dtype=object)

In [32]:
# Convert ranges like "1200-1500" to average, then make numeric
def convert_sqft(x):
    try:
        if '-' in str(x):
            vals = str(x).split('-')
            return (float(vals[0]) + float(vals[1])) / 2
        return float(x)
    except:
        return None

df['total_sqft'] = df['total_sqft'].apply(convert_sqft)

In [33]:
df['total_sqft'].unique()

array([1056. , 2600. , 1440. , ..., 1258.5,  774. , 4689. ], shape=(1997,))

In [34]:
# Extract only the number from size
df['bhk'] = df['size'].str.extract(r'(\d+)').astype(int)

In [35]:
# Remove rows where bath > bhk + 2
df = df[df['bath'] < df['bhk'] + 2]

In [36]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bhk
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056.0,2,1.0,39.07,2
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600.0,5,3.0,120.00,4
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,GrrvaGr,1440.0,2,3.0,62.00,3
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521.0,3,1.0,95.00,3
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,GrrvaGr,1200.0,2,1.0,51.00,2
...,...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453.0,4,0.0,231.00,5
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,GrrvaGr,3600.0,5,2.0,400.00,4
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141.0,2,1.0,60.00,2
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689.0,4,1.0,488.00,4
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,GrrvaGr,550.0,1,1.0,17.00,1

In [37]:
df.drop('size',axis=1,inplace=True)

In [38]:
df

,area_type,availability,location,society,total_sqft,bath,balcony,price,bhk
0,Super built-up Area,19-Dec,Electronic City Phase II,Coomee,1056.0,2,1.0,39.07,2
1,Plot Area,Ready To Move,Chikka Tirupathi,Theanmp,2600.0,5,3.0,120.00,4
2,Built-up Area,Ready To Move,Uttarahalli,GrrvaGr,1440.0,2,3.0,62.00,3
3,Super built-up Area,Ready To Move,Lingadheeranahalli,Soiewre,1521.0,3,1.0,95.00,3
4,Super built-up Area,Ready To Move,Kothanur,GrrvaGr,1200.0,2,1.0,51.00,2
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,ArsiaEx,3453.0,4,0.0,231.00,5
13316,Super built-up Area,Ready To Move,Richards Town,GrrvaGr,3600.0,5,2.0,400.00,4
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,Mahla T,1141.0,2,1.0,60.00,2
13318,Super built-up Area,18-Jun,Padmanabhanagar,SollyCl,4689.0,4,1.0,488.00,4
13319,Super built-up Area,Ready To Move,Doddathoguru,GrrvaGr,550.0,1,1.0,17.00,1

# EDA

In [39]:
df['Price_per_sqft']=round(df['price']/df['total_sqft'],2)

In [40]:
df.describe()

,total_sqft,bath,balcony,price,bhk,Price_per_sqft
count,13084.000000,13130.000000,13130.000000,13130.000000,13130.000000,13084.000000
mean,1535.374072,2.638462,1.601904,108.740129,2.782407,0.078667
std,1212.145346,1.254098,0.802262,135.979202,1.277164,1.071951
min,1.000000,1.000000,0.000000,8.000000,1.000000,0.000000
25%,1100.000000,2.000000,1.000000,50.000000,2.000000,0.040000
50%,1270.000000,2.000000,2.000000,70.090000,3.000000,0.050000
75%,1655.000000,3.000000,2.000000,118.000000,3.000000,0.070000
max,52272.000000,40.000000,3.000000,2912.000000,43.000000,120.000000

In [41]:
print(df['price'].describe())

count    13130.000000
mean       108.740129
std        135.979202
min          8.000000
25%         50.000000
50%         70.090000
75%        118.000000
max       2912.000000
Name: price, dtype: float64

In [42]:
print(df['bhk'].value_counts())

bhk
2     5524
3     4820
4     1330
1      656
5      340
6      209
7       95
8       83
9       50
10      11
11       4
27       1
19       1
16       1
43       1
14       1
12       1
13       1
18       1
Name: count, dtype: int64

In [43]:
# Plot 1: BHK Distributio
plt.figure(figsize=(7,7))
df['bhk'].value_counts().sort_index().plot(kind='bar', color='steelblue', edgecolor='black')
plt.title('BHK Distribution')
plt.xlabel('BHK')
plt.ylabel('Count')
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig('1_bhk_distribution.png')
plt.close()

In [44]:
print("\nSaved: 1_bhk_distribution.png")

Saved: 1_bhk_distribution.png

In [45]:
# Plot 2: Price Distribution
plt.figure(figsize=(8, 5))
df[df['price'] < 500]['price'].hist(bins=50, color='coral', edgecolor='black')
plt.title('Price Distribution (below 500 Lakhs)')
plt.xlabel('Price (Lakhs)')
plt.ylabel('Count')
plt.tight_layout()
plt.savefig('2_price_distribution.png')
plt.close()
print("Saved: 2_price_distribution.png")

Saved: 2_price_distribution.png

In [46]:
df.dropna(subset=['total_sqft'],inplace=True)

In [47]:
df

,area_type,availability,location,society,total_sqft,bath,balcony,price,bhk,Price_per_sqft
0,Super built-up Area,19-Dec,Electronic City Phase II,Coomee,1056.0,2,1.0,39.07,2,0.04
1,Plot Area,Ready To Move,Chikka Tirupathi,Theanmp,2600.0,5,3.0,120.00,4,0.05
2,Built-up Area,Ready To Move,Uttarahalli,GrrvaGr,1440.0,2,3.0,62.00,3,0.04
3,Super built-up Area,Ready To Move,Lingadheeranahalli,Soiewre,1521.0,3,1.0,95.00,3,0.06
4,Super built-up Area,Ready To Move,Kothanur,GrrvaGr,1200.0,2,1.0,51.00,2,0.04
...,...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,ArsiaEx,3453.0,4,0.0,231.00,5,0.07
13316,Super built-up Area,Ready To Move,Richards Town,GrrvaGr,3600.0,5,2.0,400.00,4,0.11
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,Mahla T,1141.0,2,1.0,60.00,2,0.05
13318,Super built-up Area,18-Jun,Padmanabhanagar,SollyCl,4689.0,4,1.0,488.00,4,0.10
13319,Super built-up Area,Ready To Move,Doddathoguru,GrrvaGr,550.0,1,1.0,17.00,1,0.03

In [48]:
df.to_csv(r'Banglore_clean\cleand_dataset')